default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: bitbond
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: bitbond_development

test:
  <<: *default
  database: bitbond_test

production:
  <<: *default
  database: bitbond_production
  username: bitbond
  password: <%= ENV['DB_PASSWORD'] %>
